WITH TEMP AS
(
    SELECT ITEM_ID FROM ITEM_TREE
    WHERE ITEM_ID NOT IN
    (
        SELECT DISTINCT(PARENT_ITEM_ID) FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
)

SELECT T.ITEM_ID, II.ITEM_NAME, II.RARITY 
FROM TEMP T
JOIN ITEM_INFO II USING(ITEM_ID)
ORDER BY ITEM_ID DESC;