-- FISH_INFO 에서 FISH_TYPE 별로 카운트 세서 
-- FISH_NAME_INFO 에서 이름 가져오기 

SELECT COUNT(ID) AS FISH_COUNT, 
(SELECT FISH_NAME FROM FISH_NAME_INFO WHERE FISH_TYPE=FISH_INFO.FISH_TYPE) AS FISH_NAME
FROM FISH_INFO 
GROUP BY FISH_TYPE ORDER BY FISH_COUNT DESC;