-- TODO : 각 개체의 세대 찾기 , 각 개체의 자식 수 찾기, 세대별 그룹화 

WITH RECURSIVE FIND_GENERATION AS
(
    SELECT 1 AS GENERATION,ID,PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT FIND_GENERATION.GENERATION+1,E.ID,E.PARENT_ID
    FROM ECOLI_DATA AS E
    JOIN FIND_GENERATION
    ON E.PARENT_ID=FIND_GENERATION.ID
)

# SELECT DISTINCT PARENT_ID FROM FIND_GENERATION;
SELECT COUNT(*) AS COUNT, GENERATION FROM FIND_GENERATION 
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID FROM FIND_GENERATION WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION 
ORDER BY GENERATION;