-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출(AMOUNT*PRICE) 을 조회 
-- 총매출 desc, 식품 id asc

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE*SUM(O.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O 
ON P.PRODUCT_ID=O.PRODUCT_ID 
WHERE O.PRODUCE_DATE>='2022-05-01' AND O.PRODUCE_DATE<'2022-06-01'
GROUP BY O.PRODUCT_ID ORDER BY TOTAL_SALES DESC, PRODUCT_ID;