-- 사번, 성명, 평가 등급, 성과금을 조회 
-- 사번 기준으로 오름차순 

-- 평균 점수로 계산 

SELECT HG.EMP_NO, HE.EMP_NAME,
CASE 
    WHEN AVG(HG.SCORE)>=96 THEN 'S'
    WHEN AVG(HG.SCORE)>=90 THEN 'A'
    WHEN AVG(HG.SCORE)>=80 THEN 'B'
    ELSE 'C' 
END AS GRADE, 
CASE
    WHEN AVG(HG.SCORE)>=96 THEN HE.SAL*0.2
    WHEN AVG(HG.SCORE)>=90 THEN HE.SAL*0.15
    WHEN AVG(HG.SCORE)>=80 THEN HE.SAL*0.1
    ELSE 0
END AS BONUS 
FROM HR_GRADE AS HG
JOIN HR_EMPLOYEES AS HE ON HG.EMP_NO=HE.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO;