-- GROUP BY  사원번호
-- 사원별로 평균 점수 계산해서, 등급 매기고, 성과금 계산하기 

SELECT GRADE.EMP_NO, 
EMP.EMP_NAME AS EMP_NAME,
CASE
WHEN AVG(SCORE)>=96 THEN 'S'
WHEN AVG(SCORE)>=90 THEN 'A'
WHEN AVG(SCORE)>=80 THEN 'B'
ELSE 'C'
END AS GRADE,
CASE
WHEN AVG(SCORE)>=96 THEN 0.2*EMP.SAL
WHEN AVG(SCORE)>=90 THEN 0.15*EMP.SAL
WHEN AVG(SCORE)>=80 THEN 0.1*EMP.SAL
ELSE 0
END AS BONUS
FROM HR_GRADE AS GRADE
JOIN HR_EMPLOYEES AS EMP
USING(EMP_NO)
GROUP BY EMP_NO;