SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
JOIN REST_REVIEW AS R
ON M.MEMBER_ID=R.MEMBER_ID
WHERE M.MEMBER_ID IN
(SELECT MEMBER_ID
    FROM 
     (SELECT MEMBER_ID, COUNT(*), 
     RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK 
     FROM REST_REVIEW
    GROUP BY MEMBER_ID) SQ
    WHERE RNK=1
)
ORDER BY R.REVIEW_DATE,R.REVIEW_TEXT;
