-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
WITH RANKING AS
(
    SELECT RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK, MEMBER_ID AS MEMID
    FROM REST_REVIEW GROUP BY MEMBER_ID
)

SELECT MEMBER.MEMBER_NAME, REVIEW.REVIEW_TEXT, DATE_FORMAT(REVIEW.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MEMBER
JOIN REST_REVIEW AS REVIEW
ON MEMBER.MEMBER_ID=REVIEW.MEMBER_ID
WHERE 
(SELECT RNK FROM RANKING WHERE MEMID=REVIEW.MEMBER_ID)=1
ORDER BY REVIEW_DATE, REVIEW_TEXT;