-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력
-- 물고기의 ID에 대해 오름차순 정렬
-- 종류별 group by, 거기서 제일 큰 물고기 찾아서 출력하기 
-- 이름은 서브쿼리 활용 

SELECT FI.ID, FNI.FISH_NAME,
FI.LENGTH FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE=FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN 
(SELECT FISH_TYPE,MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) 
ORDER BY FI.ID;