-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력 

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE=FNI.FISH_TYPE
WHERE FI.LENGTH =
(
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE=FI.FISH_TYPE
    GROUP BY FISH_TYPE
)
ORDER BY ID;