-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력 
WITH FIND_MAX AS (
    SELECT FISH_TYPE,MAX(LENGTH) AS LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH 
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE=FNI.FISH_TYPE
JOIN FIND_MAX ON FI.FISH_TYPE=FIND_MAX.FISH_TYPE AND FI.LENGTH=FIND_MAX.LEN
ORDER BY ID;