-- FISH_TYPE 별로 GROUP BY 
-- 평균 길이 구하기, 10CM 이하 (NULL) 는 10CM 로 처리 
-- 33CM 이상인 경우만 출력 

SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO 
GROUP BY FISH_TYPE 
HAVING SUM(IFNULL(LENGTH,10))/COUNT(ID)>33 ORDER BY FISH_TYPE;